export const GET_PROJECTS = 'GET_PROJECTS';
export const GET_TASKS = 'GET_TASKS';
export const REGISTER_PROJECT = 'REGISTER_PROJECT';
export const REGISTER_TASK = 'REGISTER_TASK';
export const ALTER_PROJECT = 'ALTER_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';