export const ADD_PROJECT = 'ADD_PROJECT';
export const ADD_TASK = 'ADD_TASK';
export const UPDATE_PROJECT = 'UPDATE_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';
export const DEFINED_PROJECT = 'DEFINED_PROJECT';
export const DEFINED_TASK = 'DEFINED_TASK';
export const NOTIFICATION = 'NOTIFICATION';